#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\Commands\Backup;
use App\Commands\BackupRestore;
use App\Commands\Migrate;
use App\Commands\MigrateRollback;
use Symfony\Component\Console\Application;

$application = new Application();
$application->setName('MotorCMS - https://motorcms.ru');

$application->addCommands([
    new Migrate(),
    new MigrateRollback(),
    new Backup(),
    new BackupRestore(),
]);

$application->run();
